### ISSUE TITLE
noetic support

### ISSUE THREAD

**Issue by finostro-amtc** [peci1/robot_body_filter#13]
Will there be noetic support?

**Comment by peci1** [comment]
Have you tried it? Did you face any problems?

**Comment by finostro-amtc** [comment]
Yes, i tried it. Without problems. 
I would like to depend on the package, but you are not on the package manager. 
It would be cleaner to add this  as a dependency if it was on the ros repositories.

**Comment by peci1** [comment]
Okay. I don't actively use Noetic on any system, so it won't be really well tested, but I can push a release. If you'll find any bugs or odd behavior, please get back here and report it.

**Comment by finostro-amtc** [comment]
sure, If I find anything I will  report back. 

Thanks!

**Comment by peci1** [comment]
Released: https://github.com/ros/rosdistro/pull/29110 . If all goes well, it will appear with the next noetic sync.

**Comment by peci1** [comment]
CI build discovered an issue with Noetic having two installs of libfcl, which is a dependency of robot_body_filter. I tried to disambiguate what version should be used. Could you try out the new version 1.1.9?

**Comment by peci1** [comment]
The binaries for Noetic have just been released.
