### ISSUE TITLE
Warnings for unset parameters

### ISSUE THREAD

**Issue by Martin-Oehler** [peci1/robot_body_filter#16]
Hey,
we recently switched back to your upstream version. Thanks for all the improvements regarding per link padding/scaling.

I noticed that each unset parameter is printed as a warning, e.g.
```
[ WARN] [1629207245.812202996]: robot_body_filter_containment: Cannot find value for parameter: bounding_sphere/publish_cut_out_pointcloud, assigning default: False
```
Since this is expected behavior and defaults are well documented, I don't see a reason for this to be a warning. This feels more like a debug message to me. We changed this in our fork tu-darmstadt-ros-pkg/robot_body_filter@2ca2a15a283da928ca18c2f1392060d826716540. What do you think about this?

Best regards,
Martin

**Comment by peci1** [comment]
Hi, I used WARN more as a visual aid than meaning a real warning. I can change it to INFO and maybe also reword the message to look less warning-y. I wouldn't like setting all parameter searches to DEBUG. Would you be okay with that?

**Comment by Martin-Oehler** [comment]
Yes, showing these messages as INFO would be better than WARN. Currently, the messages make it harder to spot real warnings. Thanks.

**Comment by peci1** [comment]
Done: 2806f5c
