### ISSUE TITLE
Question: Shortest distance from point to robot manipulator?

### ISSUE THREAD

**Issue by peda1337** [peci1/robot_body_filter#17]
Hey!
@peci1, first of all, thank you for the cool project! really appreciate it.
I am working towards workspace surveillance for industrial robots and I have a question:
With the robot_body_filter implementation present, is there a way to utilize it for implementing feature/function, which calculates the shortest distance of a point in the workspace to the robot? (already considering the kinematics and current joint angles)

Thank you and best regards,
Peter

**Comment by peci1** [comment]
Hi, there's definitely nothing dedicated - that would be more a task for some maths library. But you could utilize the segmentation of the pointcloud to point on/inside the robot body and outside of it. You could then run a search for the shortest distance between pairs of points, on from inside, one from the outside set.

**Comment by peda1337** [comment]
will try, will try.
thanks for the answer!
