### ISSUE TITLE
Per link padding and scaling not working

### ISSUE THREAD

**Issue by juansolana** [peci1/robot_body_filter#19]
Hi, I tried applying a per link scaling and padding but does not seem to be working. Do I need to reinstall the library or is something wrong with my yaml file?

```
# Filter config for segmenting out Robot from pointcloud.
# The field of view of the sensor can only capture a few links, so the `only_links` parameter is set
# to increase performance. Also, the `filter/keep_clouds_organized` parameter is important here to
# retain the 2D structure of the RGBD camera output.
# For more detail on the different parameters of the filter, refer to:
# http://wiki.ros.org/robot_body_filter
robot_filter_chain:
  - name: RobotBodyFilter
    type: robot_body_filter/RobotBodyFilterPointCloud2
    params:
      frames/fixed: 'canonical_smpl_origin'
      frames/sensor: 'canonical_smpl_origin'
      filter/keep_clouds_organized: True
      filter/do_clipping: True
      filter/do_contains_test: True
      filter/do_shadow_test: True
      sensor/point_by_point: False
      sensor/min_distance: 0.01
      sensor/max_distance: 2.5
      only_links: []
      ignored_links/everywhere: []
      body_model/inflation/scale: 1.2
      body_model/inflation/per_link/padding: {left_touchpoint: 0.072, right_touchpoint: 0.072}
      body_model/robot_description_param: '/robot_description'
      transforms/buffer_length: 15.0
      transforms/timeout/reachable: 0.2
      transforms/timeout/unreachable: 0.2
      bounding_sphere/compute: True
      bounding_sphere/debug: False
      bounding_sphere/publish_cut_out_pointcloud: True
      bounding_box/compute: True
      bounding_box/debug: False
      bounding_box/publish_cut_out_pointcloud: True
      debug/pcl/inside: False
      debug/pcl/clip: False
      debug/pcl/shadow: False
      debug/marker/contains: True
      debug/marker/shadow: False

```

**Comment by peci1** [comment]
Please, provide also the urdf of your robot

**Comment by juansolana** [comment]
This is the urdf of the robot. The collisions within `${arm_id}_touchpoint` are the ones I'm trying to apply the filter config of padding and scaling.

`<?xml version="1.0" encoding="utf-8"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="robot">
  <xacro:include filename="$(find franka_description)/robots/panda_arm.xacro"/>

  <xacro:macro name="arm" params="arm_id:='panda'">
    <link name="${arm_id}_arm_base_link"/>
    <xacro:panda_arm arm_id="${arm_id}_arm" connected_to="${arm_id}_arm_base_link" xyz="0 0 0" rpy="0 0 0"/>

    
    <link name="${arm_id}_touchpoint">
      <visual>
        <geometry>
          <mesh filename="package://description/meshes/touchpoints/${arm_id}_tp_100.stl"/>
        </geometry>
        <material name="blue">
          <color rgba="0 0  .8 1"/>
        </material>
        <origin rpy="0 0 0" xyz="0 0 0.021"/>  
      </visual>
      <collision>
        <geometry>
          <cylinder length="0.2" radius="0.05" />
        </geometry>
        <origin rpy="55 90 0" xyz="0 0 0.05"/>
        <geometry>
          <mesh filename="package://description/meshes/touchpoints/${arm_id}_tp_100.stl" scale="1.05"/>
        </geometry>
        <origin rpy="0 0 0" xyz="0 0 0.021"/>
      </collision>
    </link>

    <joint name="${arm_id}_touchpoint_joint" type="fixed">
      <parent link="${arm_id}_arm_link8"/>
      <child link="${arm_id}_touchpoint"/>
    </joint>
  </xacro:macro>

  <joint name="right_arm_base_link_calibration" type="floating">
    <parent link="left_arm_base_link"/>
    <child link="right_arm_base_link"/>
  </joint>

  <xacro:arm arm_id="right"/>
  <xacro:arm arm_id="left"/>




</robot>
`

**Comment by peci1** [comment]
The `<collision>` you posted is weird. It contains two `<geometry>` nodes, while I'm almost sure URDF only allows one geometry per collision. You can specify multiple collisions, each with a single geometry node.

**Comment by juansolana** [comment]
I guess that explains why only see the cylinder collision geometry in RViz. You think having both collision is what makes the per link `scale` and `padding` not work?

**Comment by peci1** [comment]
That's my guess. As you're using invalid URDF, many things can break and this could be one of them. Try fixing the URDF and let me know if it fixed the issue.

**Comment by peci1** [comment]
Closing this issue because there is probably not much this library can do with invalid inputs.
