### ISSUE TITLE
Cannot build robot_body_filter in ros-melodic ubuntu18.04

### ISSUE THREAD

**Issue by bohanwu** [peci1/robot_body_filter#20]
Hi,

It seems that robot_body_filter cannot be built via `catkin build robot_body_filter` in ros-meodic linux ubunt18.04 - something wrong about the const argument, qualifiers and -fpermissive. Please see stack trace below. Thank you.

In file included from src/robot_body_filter/include/robot_body_filter/RobotBodyFilter.h:16:0,
                 from /src/robot_body_filter/src/RobotBodyFilter.cpp:12:
src/robot_body_filter/include/robot_body_filter/utils/filter_utils.hpp: In instantiation of ‘T robot_body_filter::FilterBase<F>::getParamVerbose(const string&, const T&, const string&, bool*, robot_body_filter::FilterBase<F>::ToStringFn<T>) const [with T = bool; F = sensor_msgs::LaserScan_<std::allocator<void> >; std::__cxx11::string = std::__cxx11::basic_string<char>; robot_body_filter::FilterBase<F>::ToStringFn<T> = std::__cxx11::basic_string<char> (*)(const bool&)]’:
src/robot_body_filter/src/RobotBodyFilter.cpp:389:79:   required from here
src/robot_body_filter/include/robot_body_filter/utils/filter_utils.hpp:77:41: error: passing ‘const robot_body_filter::FilterBase<sensor_msgs::LaserScan_<std::allocator<void> > >’ as ‘this’ argument discards qualifiers [-fpermissive]
     if (filters::FilterBase<F>::getParam(name, value))
         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~

**Comment by peci1** [comment]
Thanks for the report, I'll investigate. It might be connected with a recent update of the filters package... What version of robot_body_filter are you using? Master branch?

**Comment by peci1** [comment]
The build runs normally on my 18.04 system. You have probably outdated ros-melodic-filters. Please, update the package to version 1.8.2 and try rebuilding this package.

**Comment by peci1** [comment]
Closed the issue due to inactivity. If it still persists after `sudo apt dist-upgrade`, please, let me know.
