### ISSUE TITLE
Reloading robot model

### ISSUE THREAD

**Issue by Patrick-Lascombe** [peci1/robot_body_filter#3]
Hello, first of all thank you for this awesome package !

I had a question about reloading the robot model by publishing on the topic /dynamic_robot_model_server/parameter_updates.

I tried to use it a few times unsuccessfully, but putting into the 'robot_model' field the path to the urdf file but received the erro 'Error document empty.'.

Do I need to to put the path to the urdf file or the content of the urdf file into the field ?

Thank you for your help

**Comment by peci1** [comment]
Hi. The field should contain the *contents* of the URDF file, not the path to it. Give it a try and let me know if it works.

**Comment by Patrick-Lascombe** [comment]
It works, thanks!
And I had another questions concerning the inner working of the node, and I didn't knew if it was better to open a new issue or to post it here.

When I'm working with cloudpoints2, are the points compared to the actual shapes of the urdf or are they compared to the bounding spheres around these shapes. I dug into the code but didn't find a clear answer to this.

**Comment by peci1** [comment]
The logic is implemented in https://github.com/peci1/robot_body_filter/blob/25014c234d44af12e6ac692c004aad174a06f7d1/src/RayCastingShapeMask.cpp#L188 .

If you enable shadow filtering, then all points have to be processed. If you only enable containment tests, there can be lots of computations saved.

Each shape, when you construct the model, constructs its bounding sphere. At the time of filtering, the model is "arranged" according to the TFs and all bounding spheres are merged. First, each point is compared to this "big sphere" (which is quite a cheap computation). Only points inside this big sphere are then passed for more detail analysis which decides whether the point lies inside the shape or not. Even in this detailed analysis, the point is first tested for being inside the shape's bounding sphere.
