### ISSUE TITLE
TF frames watchdog reachability check breaks our self-filter

### ISSUE THREAD

**Issue by schnaubelt** [peci1/robot_body_filter#5]
First of all, thank you for releasing your improved self-filter!
However, the recently introduced reachability check in the latest commit (https://github.com/peci1/robot_body_filter/commit/ee0c87fe714bf398cafbe6ae2deafd1bc5ac1a49#diff-6b286a62ec6b7077dda6d9857ec66a37R609) does not work four our setup as the sensor frame is never reachable according to the TF frames watchdog. 
This might be caused by our robot setup. We have a continuously rotating tilted VLP16 lidar and the lidar driver transforms all point clouds into a virtual fixed link located above the spinning axle. 
Therefore, our self filter config does not need to transform the point clouds during the filtering pipeline as it is already in the preferred frame. 
Also, the usage of a virtual fixed link might break the reachability check of the TF frames watchdog causing our issue of rejected scans.
Do you know, how we can fix our filtering pipeline? Or is it possible to check the necessity of a transform before querying the TF frames watchdog?

**Comment by peci1** [comment]
Hi, I'm not sure I understand your problem. So you say you get pointclouds in some frame which is unreachable from the rest of the robot? But isn't that a problem? How should the robot body be filtered out then if the filter doesn't know how to transform the robot body into the scan?

Did you try publishing a static transform between the virtual link and your robot body?

**Comment by schnaubelt** [comment]
The frame of the robot is just a frame with a fixed transform to the base_link of our robot, thus it is reachable from the rest of the robot. The problem is that the TF frames watchdog does not seem to recognize the frame as a reachable frame. 
How do you determine the reachable frames? 
Additionally, if I just comment out the "if (!this->tfFramesWatchdog->isReachable(this->sensorFrame))" check, the self-filter works again and e.g. the manipulator arm is filtered out. So, the transformations to the other links seem to be resolvable.

**Comment by peci1** [comment]
You can try in console:

    rosrun tf tf_echo robot_frame sensor_frame

**Comment by peci1** [comment]
There should be also warning in console of type `TFFramesWatchdog (%s): Frame %s is not reachable! Cause:`

What are they saying?

**Comment by schnaubelt** [comment]
This works: 
```
rosrun tf tf_echo spin_lidar_lidar_mount_link_fixed base_link
At time 0.000
- Translation: [0.264, 0.000, -0.571]
- Rotation: in Quaternion [0.000, 0.000, 0.000, 1.000]
            in RPY (radian) [0.000, -0.000, 0.000]
            in RPY (degree) [0.000, -0.000, 0.000]
```
The mentioned warning gets never posted. 
Maybe, the issue with the unreachable frame is caused by our virtual link as is does not have any geometry attached to the link in the URDF.

**Comment by peci1** [comment]
Hmm, that's weird. I'd like to figure out what's wrong here.

First - time is 0.0 - so you're running in simulation?

Second, could you please post the pdf file `frames.pdf` which is created by `rorsun tf view_frames`?

**Comment by schnaubelt** [comment]
Yes, I performed these tests in simulation only for now. I could also perform them on the real robot if this helps.

Here is our frames overview:
[frames.pdf](https://github.com/peci1/robot_body_filter/files/4154441/frames.pdf)

The fixed lidar link used for point cloud data filtering is called "spin_lidar_lidar_mount_link_fixed".

I also tried to add visual and collision geometry to our virtual fixed lidar link, such that it obtains a shape, but it did not help.

**Comment by peci1** [comment]
Could you please retest with #8? I've recently done many bugfixes to the filter code. One of them was that sensor frame is added to the frames watchdog regardless of whether is has a shape or not.

**Comment by schnaubelt** [comment]
Thank you, #8 fixes our issues.

**Comment by peci1** [comment]
Thanks for getting back. As I mentioned in #6, I'll merge #8 into master when it gets a little more tested.

**Comment by peci1** [comment]
#8 was merged to master, I'm gonna prepare a release now.
