### ISSUE TITLE
Cmake error

### ISSUE THREAD

**Issue by Praveen290192** [peci1/robot_body_filter#7]
hello,
while performing cmake I am getting below error
CMake Error at robot_body_filter/cmake/DetectOptional.cmake:4 (if):
  if given arguments:

    "CMAKE_VERSION" "VERSION_GREATER_EQUAL" "3.8"

  Unknown arguments specified
Call Stack (most recent call first):
  robot_body_filter/CMakeLists.txt:5 (include)
Can you please help me

**Comment by peci1** [comment]
Which CMake version do you use?

    cmake --version

**Comment by peci1** [comment]
Please, also provide more info about the system you are using: Linux version, ROS version, how you try to build the package (catkin_make, catkin build, other...)

**Comment by Praveen290192** [comment]
cmake version is 3.5.1
linux version ubuntu 16
ROS kinetic
platform nvidia TX2

**Comment by Praveen290192** [comment]
Hello,
after I changed the command from greater equal to greater. It does not show that error but now I am seeing below error
In file included from /usr/include/eigen3/Eigen/Core:297:0,
                 from /opt/ros/kinetic/include/eigen_stl_containers/eigen_stl_vector_container.h:40,
                 from /opt/ros/kinetic/include/eigen_stl_containers/eigen_stl_containers.h:40,
                 from /opt/ros/kinetic/include/geometric_shapes/bodies.h:45,
                 from /home/nvidia/catkin_ws/src/robot_body_filter/src/utils/bodies.cpp:6:
/usr/include/eigen3/Eigen/src/Geometry/Transform.h: In instantiation of ‘Eigen::Transform<Scalar, Dim, Mode, _Options>::Transform(const Eigen::Transform<_Scalar, Dim, OtherMode, OtherOptions>&) [with int OtherMode = 2; int OtherOptions = 0; _Scalar = double; int _Dim = 3; int _Mode = 1; int _Options = 0]’:
/home/nvidia/catkin_ws/src/robot_body_filter/src/utils/bodies.cpp:203:109:   required from here
/usr/include/eigen3/Eigen/src/Core/util/StaticAssert.h:32:40: error: static assertion failed: YOU_PERFORMED_AN_INVALID_TRANSFORMATION_CONVERSION
     #define EIGEN_STATIC_ASSERT(X,MSG) static_assert(X,#MSG);
                                        ^
/usr/include/eigen3/Eigen/src/Geometry/Transform.h:330:5: note: in expansion of macro ‘EIGEN_STATIC_ASSERT’
     EIGEN_STATIC_ASSERT(EIGEN_IMPLIES(OtherMode==int(Affine)||OtherMode==int(AffineCompact), Mode!=int(Isometry)),
     ^
In file included from /usr/include/eigen3/Eigen/Core:297:0,
                 from /usr/include/eigen3/Eigen/Dense:1,
                 from /usr/include/eigen3/Eigen/Eigen:1,
                 from /opt/ros/kinetic/include/tf2_sensor_msgs/tf2_sensor_msgs.h:36,
                 from /home/nvidia/catkin_ws/src/robot_body_filter/include/robot_body_filter/utils/tf2_sensor_msgs.h:5,
                 from /home/nvidia/catkin_ws/src/robot_body_filter/src/utils/tf2_sensor_msgs.cpp:1:
/usr/include/eigen3/Eigen/src/Geometry/Transform.h: In instantiation of ‘Eigen::Transform<Scalar, Dim, Mode, _Options>::Transform(const Eigen::Transform<_Scalar, Dim, OtherMode, OtherOptions>&) [with int OtherMode = 2; int OtherOptions = 0; _Scalar = float; int _Dim = 3; int _Mode = 1; int _Options = 0]’:
/home/nvidia/catkin_ws/src/robot_body_filter/src/utils/tf2_sensor_msgs.cpp:46:35:   required from here
/usr/include/eigen3/Eigen/src/Core/util/StaticAssert.h:32:40: error: static assertion failed: YOU_PERFORMED_AN_INVALID_TRANSFORMATION_CONVERSION
     #define EIGEN_STATIC_ASSERT(X,MSG) static_assert(X,#MSG);
                                        ^
/usr/include/eigen3/Eigen/src/Geometry/Transform.h:330:5: note: in expansion of macro ‘EIGEN_STATIC_ASSERT’
     EIGEN_STATIC_ASSERT(EIGEN_IMPLIES(OtherMode==int(Affine)||OtherMode==int(AffineCompact), Mode!=int(Isometry)),
     ^
robot_body_filter/CMakeFiles/robot_body_filter_utils.dir/build.make:62: recipe for target 'robot_body_filter/CMakeFiles/robot_body_filter_utils.dir/src/utils/bodies.cpp.o' failed
make[2]: *** [robot_body_filter/CMakeFiles/robot_body_filter_utils.dir/src/utils/bodies.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
robot_body_filter/CMakeFiles/robot_body_filter_utils.dir/build.make:206: recipe for target 'robot_body_filter/CMakeFiles/robot_body_filter_utils.dir/src/utils/tf2_sensor_msgs.cpp.o' failed
make[2]: *** [robot_body_filter/CMakeFiles/robot_body_filter_utils.dir/src/utils/tf2_sensor_msgs.cpp.o] Error 1
CMakeFiles/Makefile2:6520: recipe for target 'robot_body_filter/CMakeFiles/robot_body_filter_utils.dir/all' failed
make[1]: *** [robot_body_filter/CMakeFiles/robot_body_filter_utils.dir/all] Error 2
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2
Invoking "make -j6 -l6" failed

**Comment by peci1** [comment]
Sorry, this package doesn't officially support ROS Kinetic. It relies on many fixes done to geometric_shapes and moveit in their Melodic branches, and I'm pretty sure at least some of the fixes weren't backported to Kinetic. You may try to make this package work on Kinetic, and if you succeed, I'll make a kinetic branch here. But I don't have the resources to make the kinetic support myself.

**Comment by Praveen290192** [comment]
Do we have any other packages which can help to filter a body and work on kinetic

**Comment by peci1** [comment]
I know about http://wiki.ros.org/robot_self_filter . It's quite bound to the PR2 robot, but there's a good chance you could get it working for other robots, too. It's not as versatile as robot_body_filter, but you can give it a try. Or you can try to directly use the https://github.com/ros-planning/moveit/tree/master/moveit_ros/perception/point_containment_filter from Moveit. But as I said, it's highly probable that in Kinetic it has some bugs.
